# Generated by Django 2.1.7 on 2019-02-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meadows', '0002_auto_20190215_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ManyToManyField(related_name='meadows_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='meadow',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meadow',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='update',
            name='meadow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meadows.Meadow'),
        ),
    ]
