# Generated by Django 2.1.7 on 2019-02-15 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meadows', '0003_auto_20190215_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='created_by',
        ),
        migrations.AddField(
            model_name='update',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meadows_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
